RelativeURLs=true
CanonifyURLs=true
languageCode = "ko-KR"
defaultContentLanguage = "kr"

title = "Amazon Forecast Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://code.amazon.com/packages/Aws-workshop-template/blobs/master/--/workshop/content/"
  description = "Amazon Forecast Workshop"
  author = "Jihye Seo"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.kr]
title = "Amazon Forecast Workshop"
weight = 1
languageName = "Korean"

[[Languages.kr.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/awslabs/amazon-sagemaker-examples"
weight = 10



[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/awslabs/amazon-sagemaker-examples"
weight = 10